const std = @import("std");
const source = @import("source.zig");
const Span = source.Span;

pub const Token = struct {
    tag: Tag,
    span: Span,

    pub const keywords = std.StaticStringMap(Tag).initComptime(.{
        .{ "type", .keyword_type },
        .{ "var", .keyword_var },
        .{ "const", .keyword_const },
        .{ "module", .keyword_module },
        .{ "import", .keyword_import },
        .{ "func", .keyword_func },
        .{ "return", .keyword_return },
    });

    pub fn getKeyword(bytes: []const u8) ?Tag {
        return keywords.get(bytes);
    }
    pub const Tag = enum {
        invalid,
        eof,
        keyword_var,
        keyword_const,
        keyword_import,
        keyword_module,
        keyword_type,
        keyword_func,
        keyword_return,
        uint8,
        uint16,
        uint32,
        uint64,
        uint,
        int8,
        int16,
        int32,
        int64,
        int,
        char,
        float32,
        float64,
        float,
        boolean,
        equal,
        plus,
        minus,
        asterisk,
        percent,
        pipe,
        amperstand,
        bang,
        colon,
        semicolon,
        l_paren,
        r_paren,
        l_brace,
        r_brace,
        l_bracket,
        r_bracket,
        l_angle,
        r_angle,
        at_sign,
        identifier,
        int_literal,
        float_literal,
        multi_line_string_literal,
        string_literal,
        char_literal,
        hex_literal,
        binary_literal,
        equal_equal,
        plus_equal,
        minus_equal,
        asterisk_equal,
        slash_equal,
        slash_slash,
        amperstand_equal,
        amperstand_amperstand,
        pipe_equal,
        pipe_pipe,
        bang_equal,
        l_angle_equal,
        l_angle_l_angle,
        l_angle_l_angle_equal,
        r_angle_equal,
        r_angle_r_angle,
        r_angle_r_angle_equal,
        dot,
        dot_dot,
        dot_dot_equal,
        comma,
        underscore,

        pub fn lexeme(self: Tag) ?[]const u8 {
            return switch (self) {
                .invalid,
                .eof,
                .identifier,
                .int_literal,
                .float_literal,
                .multi_line_string_literal,
                .string_literal,
                .char_literal,
                .hex_literal,
                .binary_literal,
                => null,
                .keyword_var => "var",
                .keyword_const => "const",
                .keyword_import => "import",
                .keyword_module => "module",
                .keyword_type => "type",
                .keyword_func => "func",
                .keyword_return => "return",
                .uint8 => "u8",
                .uint16 => "u16",
                .uint32 => "u32",
                .uint64 => "u64",
                .uint => "uint",
                .int8 => "i8",
                .int16 => "i16",
                .int32 => "i32",
                .int64 => "i64",
                .int => "int",
                .char => "char",
                .float32 => "f32",
                .float64 => "f64",
                .float => "float",
                .boolean => "bool",
                .equal => "=",
                .plus => "+",
                .minus => "-",
                .asterisk => "*",
                .percent => "%",
                .pipe => "|",
                .amperstand => "&",
                .bang => "!",
                .colon => ":",
                .semicolon => ";",
                .l_paren => "(",
                .r_paren => ")",
                .l_brace => "{",
                .r_brace => "}",
                .l_bracket => "[",
                .r_bracket => "]",
                .l_angle => "<",
                .r_angle => ">",
                .at_sign => "@",
                .equal_equal => "==",
                .plus_equal => "+=",
                .minus_equal => "-=",
                .asterisk_equal => "*=",
                .slash_equal => "/=",
                .slash_slash => "//",
                .amperstand_equal => "&=",
                .amperstand_amperstand => "&&",
                .pipe_equal => "|=",
                .pipe_pipe => "||",
                .bang_equal => "!=",
                .l_angle_equal => "<=",
                .l_angle_l_angle => "<<",
                .l_angle_l_angle_equal => "<<=",
                .r_angle_equal => "=>",
                .r_angle_r_angle => ">>",
                .r_angle_r_angle_equal => ">>=",
                .dot => ".",
                .dot_dot => "..",
                .dot_dot_equal => "..=",
                .comma => ",",
            };
        }
    };
};
